Fix #656 - getProcedureName() returns a non-NULL terminated procedure name
Overview
--------

During the testing of the Ingres Ruby Frequent Flyer demo a problem
was discovered in the 'Routes' dialog. When choosing the Arriving
'Region' the following error is seen:

printGPStatus: status = IIAPI_ST_ERROR

ii_checkError: Ingres Diagnostic Messages:

ERROR: SQLSTATE: 42505, CODE: 0x965: Procedure 'get_my_airports	hu� ' not found

This change corrects getProcedureName() so that it null terminates the
procedure name being returned.

git-svn-id: http://code.ingres.com/ingres/drivers/ruby/main@3759 45b5d43f-8932-4c86-835a-3654e5842839